### ISSUE TITLE
Unable to import from EPSG for SpatialReferences

### ISSUE THREAD

**Issue by Reddevildragg** [ViRGIS-Team/gdal-upm#11]
When working with the spatial reference classes unable to import using the EPSG code directly.

`        SpatialReference src = new SpatialReference(null);
        src.ImportFromEPSG(32610)
`

However working with the eosg.io website to get either a URL or proj4 does work.
`       
 SpatialReference src = new SpatialReference(null);
        src.ImportFromUrl("https://www.epsg.io/32610.proj4");
`

not a major issue as there is a easyish workaround, from console error it looks like its trying to reference a database that is not there so not sure if there is a step/process i have missed during the installing though UPM which may be the case

**Comment by runette** [comment]
HI (sorry for the delay in the response - I went sailing for ar couple of months :).

This is not an error with the PACKAGE - so I am going to close this issue.

For reference - You will most likely find that this error happens because you have not provided either GDAL  or PROJ with the correct CERT to allow them to set up the HTTPS session. This area is a bit of a GDAL minefield ... :)

It should be :
- raised as an issue against GDAL. However - they will either say that it is an issue with the csharp bindings *which I do not think it is - since they just pass the string values to GDAL) and in which case it may get bounced back to me OR they will say it is a problem with PROJ (which is more likely the case) and direct you in that direction :) ...

- If you raise this with PROJ I have the feeling that THEY will say (most correctly) that you should not be trying to use PROJ4 strings (they have been deprecated for many years) and you should not be using the URL for EPSG codes and you SHOULD be using the direct EPSG code lookup since this accesses the optimised WKT codes from the PROJ db (which can be kept up to date through CDN access).
